project:
  type: website
  output-dir: docs
  
website:
  title: "Final-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Codes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



